# Generated by Django 5.2.3 on 2025-08-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_de_factura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_de_factura',
            name='medio_de_pago',
        ),
        migrations.RemoveField(
            model_name='tipo_de_factura',
            name='tipo_de_factura',
        ),
        migrations.AddField(
            model_name='tipo_de_factura',
            name='entryTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='entryTime'),
        ),
        migrations.AddField(
            model_name='tipo_de_factura',
            name='exitTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='exitTime'),
        ),
        migrations.AddField(
            model_name='tipo_de_factura',
            name='placa',
            field=models.TextField(blank=True, null=True, verbose_name='placa'),
        ),
        migrations.AddField(
            model_name='tipo_de_factura',
            name='rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='rate'),
        ),
    ]
