# Generated by Django 5.2.3 on 2025-08-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_de_factura', '0002_remove_tipo_de_factura_medio_de_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_de_factura',
            name='entryTime',
        ),
        migrations.RemoveField(
            model_name='tipo_de_factura',
            name='exitTime',
        ),
        migrations.RemoveField(
            model_name='tipo_de_factura',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='tipo_de_factura',
            name='rate',
        ),
        migrations.AddField(
            model_name='tipo_de_factura',
            name='paymentAmount',
            field=models.TextField(blank=True, null=True, verbose_name='paymentAmount'),
        ),
    ]
