# Generated by Django 5.2.3 on 2025-08-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_de_factura', '0003_remove_tipo_de_factura_entrytime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_de_factura',
            name='paymentAmount',
        ),
        migrations.AddField(
            model_name='tipo_de_factura',
            name='banco',
            field=models.TextField(blank=True, null=True, verbose_name='banco'),
        ),
        migrations.AddField(
            model_name='tipo_de_factura',
            name='cedula',
            field=models.TextField(blank=True, null=True, verbose_name='cedula'),
        ),
        migrations.AddField(
            model_name='tipo_de_factura',
            name='correo',
            field=models.TextField(blank=True, null=True, verbose_name='correo'),
        ),
        migrations.AddField(
            model_name='tipo_de_factura',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='tipo_de_factura',
            name='nombre',
            field=models.TextField(blank=True, null=True, verbose_name='nombre'),
        ),
    ]
