# Generated by Django 5.2.3 on 2025-08-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempodeparqueo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempodeparqueo',
            name='precio',
        ),
        migrations.AddField(
            model_name='tiempodeparqueo',
            name='entryTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='entryTime'),
        ),
        migrations.AddField(
            model_name='tiempodeparqueo',
            name='exitTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='exitTime'),
        ),
        migrations.AddField(
            model_name='tiempodeparqueo',
            name='placa',
            field=models.TextField(blank=True, null=True, verbose_name='placa'),
        ),
        migrations.AddField(
            model_name='tiempodeparqueo',
            name='rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='rate'),
        ),
    ]
