# Generated by Django 5.2.3 on 2025-08-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempodeparqueo', '0002_remove_tiempodeparqueo_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempodeparqueo',
            name='entryTime',
            field=models.TextField(blank=True, null=True, verbose_name='entryTime'),
        ),
        migrations.AlterField(
            model_name='tiempodeparqueo',
            name='exitTime',
            field=models.TextField(blank=True, null=True, verbose_name='exitTime'),
        ),
        migrations.AlterField(
            model_name='tiempodeparqueo',
            name='rate',
            field=models.TextField(blank=True, null=True, verbose_name='rate'),
        ),
    ]
